ForumManagementSystem/ForumSystem.Web/Controllers/CommentsController.cs
using ForumSystem.Data;
using ForumSystem.Data.Models;
using ForumSystem.Data.Models.Mappers;
using ForumSystem.Data.Models.ViewModels;
using ForumSystem.Services;
using ForumSystem.Services.Exceptions;
using ForumSystem.Services.Interfaces;
using ForumSystem.Services.Posts;
using ForumSystem.Web.Controllers.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForumSystem.Web.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ForumDbContext _forumDb;
        private readonly IPostService _postService;
        private readonly ICommentService _commentService;
        private readonly ForumDbContext _database;
        private readonly CommentMapper _commentMapper;
        public CommentsController(ForumDbContext forumDb, IPostService postService, ICommentService commentService, ForumDbContext database, CommentMapper commentMapper)
        {
            _forumDb = forumDb;
            _postService = postService;
            _commentService = commentService;
            _database = database;
            _commentMapper = commentMapper;
        }

        public IActionResult Create(int postId)
        {
            try
            {
                var viewModel = new CommentsModel();
                viewModel.Post = this._postService.GetById(postId);
                viewModel.PostId = postId;
                viewModel.Comments = viewModel.Post.Comments;
                return View(viewModel);
            }
            catch (EntityNotFoundException)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = $"Post with id {postId} does not exist.";

                return this.View(viewName: "Error");
            }
        }

        [HttpPost]
        public IActionResult Create(CommentsModel viewModel)
       {
            var post = this._postService.GetById(viewModel.PostId);
            viewModel.Post = post;
            var username = HttpContext.Session.GetString("CurrentUser");
            var user = _database.Users.FirstOrDefault(u => u.Username == username);
            var comment = this._commentMapper.ConvertToModel(user, viewModel);
            this._database.Comments.Add(comment);
            this._database.SaveChanges();

            return RedirectToAction("GetComments", new { postId = post.Id });
        }

        public IActionResult Edit(int commentId)
        {
            if (!this.HttpContext.Session.Keys.Contains("CurrentUser"))
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {

                var username = HttpContext.Session.GetString("CurrentUser");
                var user = _database.Users.FirstOrDefault(u => u.Username == username);
                var viewModel = new CommentsModel();

                viewModel.Comment = this._commentService.Get(user, commentId);
                viewModel.Content = viewModel.Comment.Content;
                viewModel.PostId = viewModel.Comment.Post.Id;
                viewModel.Comments = viewModel.Comment.Post.Comments;

                return View(viewModel);
            }
            catch (Exception ex)
            {
                throw new NotImplementedException();
            }
        }

        [HttpPost]
        public IActionResult Edit(CommentsModel viewModel, string Submit)
        {
            var username = HttpContext.Session.GetString("CurrentUser");
            
            viewModel.Username = username;
            viewModel.CommentId = int.Parse(Submit);
            var updatedComment = this._commentService.Update(viewModel);

            return RedirectToAction("GetComments", new { postId = updatedComment.Post.Id });
        }

        public IActionResult Delete(int commentId)
        {
            var username = HttpContext.Session.GetString("CurrentUser");
            var user = _database.Users.FirstOrDefault(u => u.Username == username);
            var comment = this._commentService.Get(user, commentId);
            this._commentService.Delete(username, commentId);

            return RedirectToAction("GetComments", new { postId = comment.Post.Id });
        }

        public IActionResult GetComments(int postId)
        {
            try
            {
                var viewModel = new CommentsModel();
                var username = HttpContext.Session.GetString("CurrentUser");
                viewModel.Post = this._postService.GetById(postId);
                viewModel.Comments = viewModel.Post.Comments;
                viewModel.PostId = postId;
                viewModel.Username = username;
                

                return View(viewModel);
            }
            catch (EntityNotFoundException)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = $"Post with id {postId} does not exist.";

                return this.View(viewName: "Error");
            }

        }
    }
}

ForumManagementSystem/ForumSystem.Web/Views/Comments/Create.cshtml
@{
    ViewData["Title"] = "Create comment";
}
@model CommentsModel

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-10">
            <h2 class="text-primary">Comments</h2>
        </div>
    </div>

    <div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Post Title
                    </th>
                    <th>
                        Post Content
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td width="33%">
                        @Model.Post.Title
                    </td>
                    <td width="49%">
                        @Model.Post.Content
                    </td>

                    <td width="18%" align="center">
                        <a asp-controller="Comments" asp-action="Create" class="btn btn-primary">
                            <i class="bi bi-plus-lg">Add comment</i>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <br />

    <form method="post">
        <div class="form-group">
            <label for="Content">Content</label>
            <textarea class="form-control" id="exampleTextarea" asp-for="Content" rows="3"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
          <br/>
          <button name="Submit" value="@Model.Post.Id" class="btn btn-primary"> Submit </button>
          <a asp-controller="Comments" asp-action="GetComments" asp-route-postId="@Model.Post.Id" class="btn btn-secondary" style="width:150px">
                Reset
            </a> 
        </div>
    </form>
    <br/>

    <div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Comment Content
                    </th>
                    <th>
                        Created By
                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td width="20%">
                            @comment.Content
                        </td>
                        <td width="30%">
                            @comment.User.Username
                        </td>

                        <td width="4%" align="center">
                            <a asp-controller="Comments" asp-action="Edit" asp-route-commentId="@comment.Id" class="btn btn-secondary">Edit</a>
                        </td>

                        <td width="4%" align="center">
                            <a asp-controller="Comments" asp-action="Delete" asp-route-commentId="@comment.Id" class="btn btn-secondary">Delete</a>
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

ForumManagementSystem/ForumSystem.Web/Views/Comments/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

ForumManagementSystem/ForumSystem.Web/Views/Comments/Edit.cshtml
@{
    ViewData["Title"] = "Edit comment";
}
@model CommentsModel

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-10">
            <h2 class="text-primary">Comments</h2>
        </div>
    </div>

    <div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Post Title
                    </th>
                    <th>
                        Post Content
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td width="33%">
                        @Model.Comment.Post.Title
                    </td>
                    <td width="49%">
                        @Model.Comment.Post.Content
                    </td>

                    <td width="18%" align="center">
                        <a asp-controller="Comments" asp-action="Create" class="btn btn-primary">
                            <i class="bi bi-plus-lg">Add comment</i>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <br />
    
    <form asp-controller ="Comments" method="post" asp-action="Edit">
        
          <div>
              <div class="form-group">
            <label for="">Content</label>
            <input class="form-control" asp-for="Content" rows="3" />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
           
            <button name="Submit" value="@Model.Comment.Id" class="btn btn-primary"> Save </button>
          <a asp-controller="Comments" asp-action="Delete" asp-route-postId="@Model.Comment.Post.Id" class="btn btn-secondary" style="width:150px">
                Delete
            </a> 
        </div>
    </form>
    <br/>

    <div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Comment Content
                    </th>
                    <th>
                        Created By
                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td width="20%">
                            @comment.Content
                        </td>
                        <td width="30%">
                            @comment.User.Username
                        </td>

                        <td width="4%" align="center">
                            <a asp-controller="Comments" asp-action="Edit" asp-route-commentId="@comment.Id" class="btn btn-secondary">Edit</a>
                        </td>

                        <td width="4%" align="center">
                            <a asp-controller="Comments" asp-action="Delete" asp-route-commentId="@comment.Id" class="btn btn-secondary">Delete</a>
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

ForumManagementSystem/ForumSystem.Web/Views/Comments/GetComments.cshtml
@{
    ViewData["Title"] = "Comments";
    bool isAdmin = this.Context.Session.GetString("Role") == "Admin";
}
@model CommentsModel

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-10">
            <h2 class="text-primary">Comments</h2>
        </div>
    </div>

    <div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Post Title
                    </th>
                    <th>
                        Post Content
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td width="33%">
                        @Model.Post.Title
                    </td>
                    <td width="49%">
                        @Model.Post.Content
                    </td>

                    <td width="18%" align="center">
                        <a asp-controller="Comments" asp-action="Create" asp-route-postId="@Model.Post.Id" class="btn btn-primary">
                            <i class="bi bi-plus-lg">Add comment</i>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <br />

    <div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Comment Content
                    </th>
                    <th>
                        Created By
                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td width="20%">
                            @comment.Content
                        </td>
                        <td width="30%">
                            @comment.User.Username
                        </td>

                        @{
                            if (isAdmin || comment.User.Username == @Model.Username)
                            {
                                <td width="4%" align="center">
                                    <a asp-controller="Comments" asp-action="Edit" asp-route-commentId="@comment.Id" class="btn btn-secondary">Edit</a>
                                </td>

                                <td width="4%" align="center">
                                    <a asp-controller="Comments" asp-action="Delete" asp-route-commentId="@comment.Id" class="btn btn-secondary">Delete</a>
                                </td>
                            }
                        }
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <div class="p-3">
        <a asp-controller="Posts" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to All Posts
        </a>
    </div>
</div>